### ISSUE TITLE
Crash with .NET 4.7.2

### ISSUE THREAD

**Issue by steronydh** [Code-Artist/MSChartExtension#13]
My .NET 4.7.2 C# program crashes when I select "Clear Cursors" with v3.2.0. I tried version 2.1.0 and that crashes when you drag a rectangle to zoom in. It's fine with v1.4.1.

**Comment by Code-Artist** [comment]
The reported issue was not reproducible with MSChartExtensionDemo switched to .NET 4.7.2.
Please check if you see the same issue with MSChartExtensionDemo.
Alternatively, if you don't mind to share your code in a private GitHub project, maybe I can look into your code what is causing the crashes.

**Comment by steronydh** [comment]
Hi, 

I tried the Demo and didn't get the same error, however if I click on Clear Data and then Log Test  on the Line Chart page I get this error: 

Chart Area Axes - A logarithmic scale cannot be used for this axis.

**Comment by steronydh** [comment]
I can reproduce my error with a new project, using VS 2019 16.4.5:

- Create a new C# forms app with .net framework
- Use Nuget to install MSChartExtension 3.2.0
- Add a chart to the form
- Add event handler Form1_Shown:

```
        private void Form1_Shown(object sender, EventArgs e)
        {
            chart1.EnableZoomAndPanControls();

            chart1.Series[0].Points.AddXY(0, 0);
            chart1.Series[0].Points.AddXY(10, 10);
            chart1.Series[0].Points.AddXY(20, 5);
            chart1.Series[0].Points.AddXY(30, 40);
        }
```
- Compile and Run
- Right click and select 'Clear cursors...'
- Get an exception "object is not set to an instance of an object"

Hope that helps. I get the error whether I set the .Net Framework version to 4.8 or 4.0.

**Comment by Code-Artist** [comment]
Thanks for your input. We can now reproduce the issue your reported.
We will look into this.

**Comment by Code-Artist** [comment]
Thanks for your suggestion, We implemented fix as per your suggestion.
Released updated package Version 3.2.1

**Comment by steronydh** [comment]
Great, thank you!

**Comment by Code-Artist** [comment]
Welcome.
