### ISSUE TITLE
Programmatically select Cursor select series

### ISSUE THREAD

**Issue by kravlost** [Code-Artist/MSChartExtension#14]
Hi, is there a way to set the Select Cursor 1 series programmatically?

![image](https://user-images.githubusercontent.com/4245329/92089956-be493e00-edc6-11ea-8e7b-6401f485a72e.png)

Thanks!

**Comment by Code-Artist** [comment]
Hello @steronydh ,

Sorry for late reply. Can you describe in more details what you trying to achieve?
Is that true you want to select Cursor 1 on selected series by code after the chart had been updated?

**Comment by steronydh** [comment]
@Code-Artist Yes, for example if I have two series I want to make Cursor1 select Series 2 programmatically after adding the two series.

**Comment by Code-Artist** [comment]
@steronydh, selected series of each cursor is defined by in `ChartTool[<ChartName>].CursorX.SelectedChartSeries.` You may want to create a public method to assign series to these 2 properties.
