### ISSUE TITLE
Change: Select should create a selection area (like zoom)

### ISSUE THREAD

**Issue by pckujawa** [Code-Artist/MSChartExtension#3]
I've already implemented the code, but I figured that I would start a discussion. Maybe there's a good reason why selection should only be one point and I'm not thinking of it.

The way I implemented it, the callback is made on the MouseUp event rather than MouseDown (the previous method). This way, the callback (whose signature now just sends a RectangleF) is called only once with the complete selection area information. This may break existing code that relied on SelectionChanged being called on MouseDown, but I doubt it.

To supplement this new selection style, I wrote a method that returns the DataPoints within the selected area, which is clearly a useful thing.

**Comment by Code-Artist** [comment]
Review:
1. Select data point nearest to cursor on mouse click implemented in SnapToNearestData where data is returned in CursorPositionChanged callback.
2. Multi select is not planned, dropped for now.
