### ISSUE TITLE
Ideas: Callback for PanFinished and new architecture to facilitate changes

### ISSUE THREAD

**Issue by pckujawa** [Code-Artist/MSChartExtension#8]
Along the lines of some of the work done with ZoomChanged, wherein the client's callback receives the extents of the visible data, I was thinking that a callback once the user has stopped panning would be in order.

A scenario would be that the client wants to update statistics (say mean, standard deviation, min/max, etc) on the visible data. Currently, she or he can use the ZoomChanged callback to receive this information any time the chart is zoomed. But if the user pans, we have no mechanism in place (unless I'm missing something) to ensure that the client is notified that the visible extents of the chart have changed. Now, one option is for the client to just wire up a button saying "Recalculate Statistics," but I think an event or callback would result in a more user-friendly interface.

Lastly, in order to facilitate this and future changes, it might be wise to return a `ChartController` object from the `EnableZoomAndPanControls()` method. Then we could use that object to subscribe to events, enable/disable context menu items, and maybe more. I haven't thought it through too much, but I feel that this method would make it easier to introduce new features without breaking backwards-compatibility (and without adding too many parameters to the extension method).

Anyway, just some ideas to discuss, so please leave feedback.
Thanks,
Pat

**Comment by Code-Artist** [comment]
NOTE: `ZoomChanged `event will remain as event for view changed result from Zoom and Pan.
